version: '3.8'

services:

  postgres:
    image: postgres:15

    container_name: airflow-postgres

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  airflow:
    image: apache/airflow:2.8.3

    container_name: airflow

    depends_on:
      - postgres

    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow123@postgres:5432/airflow

      AIRFLOW__CORE__LOAD_EXAMPLES: "False"

      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"

      # Dashboard Login
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_PASSWORD}

    command: standalone

    restart: unless-stopped

volumes:
  postgres_data: